[package]
name = "redox_users"
version = "0.1.0"
authors = ["Jose Narvaez <goyox86@gmail.com>", "Wesley Hershberger <mggmugginsmc@gmail.com>"]
description = "A Rust library to access Redox users and groups functionality"
license = "MIT"
repository = "https://github.com/redox-os/users"
documentation = "https://docs.rs/redox_users"
readme = "README.md"
keywords = ["redox", "auth"]

[dependencies]
argon2rs = { version = "0.2", default-features = false }
rand = "0.4"
redox_syscall = "0.1"
failure = "0.1.1"

[target.'cfg(not(target_os = "redox-os"))'.dependencies]
fs2 = "0.4.3"
